from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.implicitly_wait(5)
driver.execute_script("window.scrollBy(0, 600);")
btn_1 = driver.find_element_by_css_selector("[title = 'Selenium Ruby']").click()
driver.execute_script("window.scrollBy(0, 800);")
btn_2 = driver.find_element_by_css_selector(".reviews_tab").click()
driver.execute_script("window.scrollBy(0, 800);")
btn_3 = driver.find_element_by_css_selector(".star-5").click()
btn_4 = driver.find_element_by_id("comment").send_keys("Nice Book!")
btn_5 = driver.find_element_by_id("author").send_keys("Nikita")
btn_6 = driver.find_element_by_id("email").send_keys("Nikita@mail.ru")
btn_7 = driver.find_element_by_id("submit").click()
